### ISSUE TITLE
"does not expand into a subdirectory" error when running config with `"weights_file": "resnet50_imagenet_v1.pth"`

### ISSUE THREAD

**Issue by Embeddave** [twosixlabs/armory#1566] opened 2022-06-14 17:34 UTC
Hi armory devs,

I'm trying to run the attached config but I get a surprising error.
[imagenette-resnet50.json.zip](https://github.com/twosixlabs/armory/files/8902144/imagenette-resnet50.json.zip)

What I'm trying to do is run an image classification scenario, using the Imagenette dataset, with the pytorch resnet50 pre-trained on ImageNet

The error I get is:
```
PermissionError: resnet50_imagenet_v1.pth does not expand into a subdirectory. Weights files submitted as tarballs must expand into a subdirectory.
```

I might be wrong but it looks like what's happening is that the weights path is for some reason considered a tarfile and then it tries to unpack it?
See this line in `armory.data.utils.maybe_download_weights_from_s3`:  
https://github.com/twosixlabs/armory/blob/87a5301ef2a521aa187a210a14e1a1f74c287d00/armory/data/utils.py#L87
Somehow it must evaluate to `True` for us to get to the error message
The entire traceback, if it helps:
```
ubuntu@ip-172-31-29-19:~/repos/gard/eval5$ armory run data/configs/imagenette_resnet50.json
2022-06-14 17:17:26  0s INFO     armory.eval.evaluator:__init__:32 Constructing Evaluator Object
2022-06-14 17:17:26  0s INFO     armory.eval.evaluator:__init__:63 Retrieving Environment Variables
2022-06-14 17:17:26  0s INFO     armory.docker.images:ensure_image_present:154 Retrieved canonical image name for twosixarmory/pytorch as twosixarmory/pytorch:0.15.3
2022-06-14 17:17:26  0s INFO     armory.docker.images:ensure_image_present:165 image twosixarmory/pytorch:0.15.3 not found. downloading...
2022-06-14 17:17:26  0s INFO     armory.docker.images:pull_verbose:203 docker pulling from twosixarmory/pytorch:0.15.3 use '--log=progress' to see status
2022-06-14 17:19:33 2m7s SUCCESS  armory.docker.images:pull_verbose:207 pulled twosixarmory/pytorch:0.15.3
2022-06-14 17:19:35 2m9s INFO     armory.docker.management:__init__:62 ARMORY Instance f203a96bde created.
2022-06-14 17:19:35 2m9s INFO     armory.eval.evaluator:_run_config:272 Running evaluation script
2022-06-14 17:19:35  0s INFO     armory.delayed_imports:<module>:7 Importing and configuring torch, tensorflow, and art, if available. This may take some time.
2022-06-14 17:19:37.698032: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-14 17:19:37.699205: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-14 17:19:37.699902: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:936] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2022-06-14 17:19:37  2s INFO     armory.delayed_imports:<module>:30 Setting tf.config.experimental.set_memory_growth to True on all GPUs
2022-06-14 17:19:37  2s INFO     art.config:set_data_path:55 set ART_DATA_PATH to /tmp/.art/data
2022-06-14 17:19:38  3s INFO     art.config:set_data_path:55 set ART_DATA_PATH to /armory/saved_models/art
2022-06-14 17:19:38  3s WARNING  __main__:<module>:213 armory calling version 0.15.3 != armory imported version 0.0.0
2022-06-14 17:19:38  3s INFO     armory.data.utils:maybe_download_weights_from_s3:49 resnet50_imagenet_v1.pth not found in Armory `saved_model_dir`. Attempting to pull weights from S3
2022-06-14 17:19:38  3s INFO     armory.data.utils:download_file_from_s3:130 downloading S3 data file armory-public-data/model-weights/resnet50_imagenet_v1.pth
2022-06-14 17:19:39  4s ERROR    armory.scenarios.scenario:evaluate:397 Encountered error during scenario evaluation.
Traceback (most recent call last):
File "/opt/conda/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
│         │     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
│         └ <code object <module> at 0x7fd4e3db4660, file "/opt/conda/lib/python3.8/site-packages/armory/scenarios/main.py", line 1>
└ <function _run_code at 0x7fd621fadd30>
File "/opt/conda/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
│     └ {'__name__': '__main__', '__doc__': '\nMain script for running scenarios. Users will run a scenario by calling:\n    armory r...
└ <code object <module> at 0x7fd4e3db4660, file "/opt/conda/lib/python3.8/site-packages/armory/scenarios/main.py", line 1>
File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/main.py", line 228, in <module>
run_config(
└ <function run_config at 0x7fd4e2b92040>
File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/main.py", line 144, in run_config
scenario.evaluate()
│        └ <function Scenario.evaluate at 0x7fd4e29003a0>
└ <armory.scenarios.image_classification.ImageClassificationTask object at 0x7fd621681910>
> File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 388, in evaluate
self._evaluate()
│    └ <function Scenario._evaluate at 0x7fd4e2900310>
└ <armory.scenarios.image_classification.ImageClassificationTask object at 0x7fd621681910>
File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 377, in _evaluate
self.load()
│    └ <function Scenario.load at 0x7fd4e2919e50>
└ <armory.scenarios.image_classification.ImageClassificationTask object at 0x7fd621681910>
File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 271, in load
self.load_model()
│    └ <function Scenario.load_model at 0x7fd4e29199d0>
└ <armory.scenarios.image_classification.ImageClassificationTask object at 0x7fd621681910>
File "/opt/conda/lib/python3.8/site-packages/armory/scenarios/scenario.py", line 109, in load_model
model, _ = config_loading.load_model(model_config)
│              │          └ {'fit': False, 'fit_kwargs': {'nb_epochs': 20}, 'model_kwargs': {}, 'module': 'armory.baseline_models.pytorch.resnet50', 'nam...
│              └ <function load_model at 0x7fd4e2c10a60>
└ <module 'armory.utils.config_loading' from '/opt/conda/lib/python3.8/site-packages/armory/utils/config_loading.py'>
File "/opt/conda/lib/python3.8/site-packages/armory/utils/config_loading.py", line 94, in load_model
weights_path = maybe_download_weights_from_s3(
└ <function maybe_download_weights_from_s3 at 0x7fd4e2c46ca0>
File "/opt/conda/lib/python3.8/site-packages/armory/data/utils.py", line 95, in maybe_download_weights_from_s3
raise PermissionError(
PermissionError: resnet50_imagenet_v1.pth does not expand into a subdirectory. Weights files submitted as tarballs must expand into a subdirectory.
2022-06-14 17:19:40 2m14s ERROR    armory.docker.management:exec_cmd:105 command python
```

**Comment by lcadalzo** [comment] 2022-06-14 21:44
First, as an aside, I noticed that the config doesn't meet the Armory config schema (and in fact isn't valid JSON) until I added the necessary pieces based on the error messages I was seeing.

(1)
```
2022-06-14 15:25:59  0s ERROR    __main__:run:369 Could not decode 'david_n_debugging/imagenette-resnet50.json' as a json file.
```

(2)
```
2022-06-14 15:27:01  0s ERROR    __main__:run:361 Could not validate config: 'defense' is a required property @ 
```

(3)
```
2022-06-14 15:27:17  0s ERROR    __main__:run:361 Could not validate config: 'name' is a required property @ dataset

```

After fixing these, I'm able to reproduce the error. This is the output of a script I wrote that prints `tarfile.is_tarfile(filepath)` for each `filepath` in my `~/.armory/saved_models`:

```
carla_rgb_weights.pt False
inceptionresnetv2_imagenet_v1.h5 False
xview_model_state_dict_epoch_99_loss_0p67 False
densenet121_imagenet_v1.h5 False
resnet50_imagenet_v1.h5 False
crop8_model_snapshot_99.pth False
carla_multimodal_robust_weights_eval5.pt False
carla_multimodal_naive_weights.pt False
cifar10_explanatory_model_resnet18_bean.pt False
resnet50_imagenet_v1.pth True
carla_rgb_weights_eval5.pt False
pytorch_goturn.pth.tar False
undefended_mnist_5epochs.pth False
mars_ucf101_v1.pth False
gtsrb_explanatory_model_micronnet_bean.pt False
multimodal_baseline_weights.h5 False
resisc10_explanatory_model_resnet18_bean.pt False
sincnet_librispeech_v1.pth False
densenet121_resisc45_v1.h5 False
gard-submissions-saved-models.tar True
carla_multimodal_robust_clw_1_weights.pt False
carla_depth_weights.pt False
mars_kinetics_v1.pth False
undefended_mnist_5epochs.h5 False
```

I'm not immediately sure why `resnet50_imagenet_v1.pth` yields `True` unlike every other weights file. It seems likely this error hasn't come up yet simply because nobody has used this file, of which I'll need to try and find more context on

**Comment by Embeddave** [comment] 2022-06-15 00:04
@lcadalzo is `torchvision` built into the armory-pytorch?
I don't even see `torch` in the Dockerfile, I guess it's hidden in requirements.txt or something?
https://github.com/twosixlabs/armory/blob/master/docker/Dockerfile-pytorch

I'm wondering if I could just load weights + model directly from `torchvision` without needing to do anything extra, i.e. if I can just specify `torchvision.models.resnet50` in the models section and then literally write the url from their hub as the weights path.
My guess is that's where the file came from originally anyway

**Comment by lcadalzo** [comment] 2022-06-15 16:53
Unfortunately I wasn't able to find much context on the file, as it was uploaded to s3 in April of 2020. I agree the file likely came from a source as you describe, I'm pretty confident it wasn't trained by a former Two Six person and then uploaded. Scouring the internet for the file didn't lead to anything for me

R.e. `torchvision`, this is [included](https://github.com/twosixlabs/armory/blob/v0.15.3/docker/Dockerfile-base#L49) in Armory's PyTorch container. I agree you definitely should be able to load a pretrained model via a torchvison call, perhaps via the **_pretrained_** kwarg as indicated [here](https://pytorch.org/vision/stable/generated/torchvision.models.resnet50.html#torchvision.models.resnet50)

**Comment by Embeddave** [comment] 2022-06-15 17:32
Thank you @lcadalzo I do see that `armory.baseline_models.pytorch` includes the`resnet50` model from `torchvision`

https://github.com/twosixlabs/armory/blob/master/armory/baseline_models/pytorch/resnet50.py

so yes I could pass in `"pretrained": true` in the config via `model_kwargs` which is what I think you're suggesting, or download weights manually and pass them in as `weights_path` with the config file

I'd suggest removing the file to close this just so no-one else runs into the same issue?

also ran into an issue with the dataset in #1567

**Comment by lcadalzo** [comment] 2022-06-15 18:25
agreed, I've removed the file and will close this issue

**Closed by lcadalzo** 2022-06-15 18:25 UTC
