### ISSUE TITLE
Support --gpus argument for Docker 19+

### ISSUE THREAD

**Issue by GuillaumeLeclerc** [twosixlabs/armory#157] opened 2020-02-14 14:07 UTC
The CLI interface to run docker containers with GPU has changed since version 19 of Docker. On this line https://github.com/twosixlabs/armory/blob/d275056fa1b8b6c478047a0b1bd3d0a1a14fc73f/armory/eval/evaluator.py#L36 the `--runtime=nvidia` argument is used. This has been depreciated and the correct argument to use from version 19 and onwards is `--gpus all` (all can be replaced by the list of GPUs).

**Comment by seanpmorgan** [comment] 2020-02-17 16:00
Pending https://github.com/docker/docker-py/pull/2471

**Comment by seanpmorgan** [comment] 2020-03-20 18:25
Seeing as the docker-py PR has stagnated, we need to determine the instructions for installing "nvidia" runtime on docker19 so that method can be used.

**Comment by seanpmorgan** [comment] 2020-03-25 20:29
@GuillaumeLeclerc Apologies for the slow turn around on this. It looks as though the runtime argument was deprecated prematurely since there is no support for --gpus argument in docker-py or docker-compose (both heavily used methods for launching docker containers).

You should be able to utilize the runtime argument on Docker 19+ as long as it is installed and configured in the daemon configuration file:

**Method 1:**
Install nvidia-docker2 package
https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)#ubuntu-distributions-1

**Method 2:**
Install the container runtime:
https://github.com/NVIDIA/nvidia-container-runtime#ubuntu-distributions

Modify the config file:
https://github.com/NVIDIA/nvidia-container-runtime#daemon-configuration-file


Please see this docker-compose issue for more details:
https://github.com/docker/compose/issues/6691

Please let us know if you're unable to install the runtime from either of these methods.

**Comment by GuillaumeLeclerc** [comment] 2020-04-16 03:27
Method 2 worked for me. I don't know if you want to close this issue or not.

**Comment by seanpmorgan** [comment] 2020-04-16 03:28
> Method 2 worked for me. I don't know if you want to close this issue or not.

Glad to hear. We'll leave it open because we want to switch to the new method as soon as we're able to. Thanks for reporting.

**Comment by seanpmorgan** [comment] 2020-07-15 16:40
https://github.com/docker/docker-py/pull/2471 has been approved. Once this merges we can update armory accordingly.

**Comment by Lodour** [comment] 2021-03-16 22:28
Hello, the docker-py PR has been merged.
Is there any plan to update this dependency?

**Comment by mzweilin** [comment] 2022-01-13 06:10
I encountered the same issue. I hope this will be fixed soon @davidslater

**Comment by davidslater** [comment] 2022-01-13 16:37
@mzweilin can you provide a stack trace for the issue you have?

I am unable to reproduce:
```
(anaconda3)david.slater@noether:~$ python
Python 3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import docker
>>> docker.__version__
'5.0.0'
>>> exit()
(anaconda3)david.slater@noether:~$ docker --version
Docker version 20.10.2, build 20.10.2-0ubuntu1~20.04.3
(anaconda3)david.slater@noether:~$ cd armory
(anaconda3)david.slater@noether:~/armory$ armory run scenario_configs/mnist_baseline.json --gpus=7
2022-01-13 16:35:51 noether armory.__main__[1032683] INFO --gpus field specified. Setting --use-gpu to True
2022-01-13 16:35:53 noether armory.docker.management[1032683] INFO ARMORY Instance 1130f7b52e created.
2022-01-13 16:35:53 noether armory.eval.evaluator[1032683] INFO Running evaluation script
...
```

It works fine and uses the GPU.

**Comment by davidslater** [comment] 2022-01-13 23:12
So in Docker 19+, you would just use runtime "runc" and the GPU would just work?

Do you know if there is an easy way to check for nvidia-container-toolkit?

**Comment by mzweilin** [comment] 2022-01-14 06:54
> So in Docker 19+, you would just use runtime "runc" and the GPU would just work?

Yes, if you have `nvidia-container-toolkit` and you specify something like `--gpus all` to the Docker CLI.


> Do you know if there is an easy way to check for nvidia-container-toolkit?

Both `nvidia-container-runtime` and `nvidia-container-toolkit` are executables that can be located by `which ?`.

If a system has `nvidia-container-runtime` (and the `nvidia` runtime is configured correctly), the current Armory should run flawlessly. 

If a system doesn't have `nvidia-container-runtime` but `nvidia-container-toolkit`, the `runtime=nvidia` parameter wouldn't work. We should use the `device_requests` argument instead in `client.containers.run()` to expose GPUs, as in https://github.com/docker/docker-py/pull/2471 Basically, Armory would need to do some argument translation.

**Comment by shenshaw26** [comment] 2022-04-26 21:18
Ok, so here are my notes so far.  To recreate this issue:

First lets show that the old way (`nvidia-container-runtime=2.0.0+docker18.03.1-1` and `docker-ce=5:18.09.9~3-0~ubuntu-bionic` aka Docker 18) works:
```bash
sudo apt-get remove docker docker-engine docker.io containerd runc nvidia-container-runtime
sudo apt-get install nvidia-container-runtime=2.0.0+docker18.03.1-1
sudo apt-get install docker-ce=5:18.09.9~3-0~ubuntu-bionic docker-ce-cli=5:18.09.9~3-0~ubuntu-bionic containerd.io docker-compose-plugin
armory run cifar10_baseline.json --use-gpu --gpu all --check
```

 and worked.  However if you upgrade to

**Comment by davidslater** [comment] 2022-04-27 00:28
@mzweilin can you weigh in here?

**Closed** 2022-12-05 19:13 UTC
Labels: docker, configuration files
