### ISSUE TITLE
[BUG]: flake8 checks untracked files in repository

### ISSUE THREAD

**Issue by ppark-twosixtech** [twosixlabs/armory#1751] opened 2022-11-09 01:31 UTC
### Description of the bug

Executing a git commit ends with error messages from `flake8` for untracked files, which I can reproduce by executing `python -m flake8` in the repo (see Steps To Reproduce for command line execution and output).

Note that for me, `source tools/pre-commit.sh` threw the following error message `.git/hooks/pre-commit: 1: source: not found` when trying to commit, and the way I worked around this (after googling) was to switch to `. tools/pre-commit.sh`. `source tools/pre-commit.sh` works from the command line however, but exits the shell connection at the end (another mystery to me).

In theory, what I would expect is flake8 to work on the changed files that `git status -s` would tell me about, and if I were to run `python -m flake8 $(git status -s | grep -Ev '\?\?' | cut -c 4- )`, it does seem to act on the 3 files that were changed. Notice, however that this time, `flake8` throws an error for `armory/utils/config_schema.json`, which it did not do for the previous commit attempt. Again, it is unclear to me what `flake8` is targeting with the configuration set up in `.flake8` and how it works within the context of the overall commit and prehook process.

### Steps To Reproduce

```
(armory_repo) (base) paul.park@noether:~/repositories/armory$ git status
On branch pp/tide
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   armory/metrics/task.py
	modified:   armory/scenarios/main.py
	modified:   armory/utils/config_schema.json

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	dev_notes/
	tide_integration_test.ipynb

(armory_repo) (base) paul.park@noether:~/repositories/armory$ cat .git/hooks/pre-commit
. tools/pre-commit.sh

(armory_repo) (base) paul.park@noether:~/repositories/armory$ git commit -m "tested adding new metric task to scenario; tested importing tidecv and converting armory output into TIDE input within new task definition for a single image - need to generalize for a list of images; need to determine what to return and in what format to be compatible with post-processing that seems to happen after the call is done"
./.ipynb_checkpoints/metrics-checkpoint.py:5:1: E302 expected 2 blank lines, found 1
./.ipynb_checkpoints/metrics-checkpoint.py:37:1: E302 expected 2 blank lines, found 1
./.ipynb_checkpoints/metrics-checkpoint.py:142:1: E302 expected 2 blank lines, found 1
./.ipynb_checkpoints/metrics-checkpoint.py:164:5: F841 local variable 'RECALL_POINTS' is assigned to but never used
./.ipynb_checkpoints/metrics-checkpoint.py:206:5: F841 local variable 'average_precisions_by_class' is assigned to but never used
./.ipynb_checkpoints/metrics-checkpoint.py:207:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:210:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:290:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:291:9: E303 too many blank lines (2)
./.ipynb_checkpoints/metrics-checkpoint.py:293:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:295:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:300:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:513:39: W292 no newline at end of file
./dev_notes/metrics.py:165:5: F841 local variable 'RECALL_POINTS' is assigned to but never used
./dev_notes/metrics.py:207:5: F841 local variable 'average_precisions_by_class' is assigned to but never used
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:5:1: E302 expected 2 blank lines, found 1
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:37:1: E302 expected 2 blank lines, found 1
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:142:1: E302 expected 2 blank lines, found 1
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:164:5: F841 local variable 'RECALL_POINTS' is assigned to but never used
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:206:5: F841 local variable 'average_precisions_by_class' is assigned to but never used
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:207:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:210:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:290:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:291:9: E303 too many blank lines (2)
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:293:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:295:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:300:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:513:39: W292 no newline at end of file

(armory_repo) (base) paul.park@noether:~/repositories/armory$ python -m flake8
./.ipynb_checkpoints/metrics-checkpoint.py:5:1: E302 expected 2 blank lines, found 1
./.ipynb_checkpoints/metrics-checkpoint.py:37:1: E302 expected 2 blank lines, found 1
./.ipynb_checkpoints/metrics-checkpoint.py:142:1: E302 expected 2 blank lines, found 1
./.ipynb_checkpoints/metrics-checkpoint.py:164:5: F841 local variable 'RECALL_POINTS' is assigned to but never used
./.ipynb_checkpoints/metrics-checkpoint.py:206:5: F841 local variable 'average_precisions_by_class' is assigned to but never used
./.ipynb_checkpoints/metrics-checkpoint.py:207:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:210:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:290:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:291:9: E303 too many blank lines (2)
./.ipynb_checkpoints/metrics-checkpoint.py:293:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:295:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:300:1: W293 blank line contains whitespace
./.ipynb_checkpoints/metrics-checkpoint.py:513:39: W292 no newline at end of file
./dev_notes/metrics.py:165:5: F841 local variable 'RECALL_POINTS' is assigned to but never used
./dev_notes/metrics.py:207:5: F841 local variable 'average_precisions_by_class' is assigned to but never used
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:5:1: E302 expected 2 blank lines, found 1
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:37:1: E302 expected 2 blank lines, found 1
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:142:1: E302 expected 2 blank lines, found 1
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:164:5: F841 local variable 'RECALL_POINTS' is assigned to but never used
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:206:5: F841 local variable 'average_precisions_by_class' is assigned to but never used
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:207:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:210:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:290:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:291:9: E303 too many blank lines (2)
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:293:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:295:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:300:1: W293 blank line contains whitespace
./dev_notes/.ipynb_checkpoints/metrics-checkpoint.py:513:39: W292 no newline at end of file

(armory_repo) (base) paul.park@noether:~/repositories/armory$ git status -s | grep -Ev '\?\?' | cut -c 4-
armory/metrics/task.py
armory/scenarios/main.py
armory/utils/config_schema.json

(armory_repo) (base) paul.park@noether:~/repositories/armory$ python -m flake8 $(git status -s | grep -Ev '\?\?' | cut -c 4- )
armory/utils/config_schema.json:112:25: F821 undefined name 'null'
```

**Comment by davidslater** [comment] 2022-11-09 16:47
The main issue here should be fixed in `rc0.16.1`:

In particular, we filter based on this line:
https://github.com/twosixlabs/armory/blob/rc0.16.1/tools/pre-commit.sh#L18

**Comment by lcadalzo** [comment] 2022-11-09 16:55
@ppark-twosixtech can you clarify how you got around the `.git/hooks/pre-commit: 1: source: not found` error? You changed your `.git/hooks/pre-commit` file to the following?
```
. tools/pre-commit.sh
```

I'm on the updated `rc0.16.1` branch and running into the same error when trying to reproduce your findings:
```
(armory) lucas@ubu0953:~/Desktop/gard/git/twosixlabs/armory$ git commit -m "foo"
.git/hooks/pre-commit: 1: source: not found

```

**Comment by davidslater** [comment] 2022-11-09 17:03
@christopherwoodall looks like we're running into shell issues.

**Comment by davidslater** [comment] 2022-11-09 17:14
Paul was also running into this issue:
```
$ git commit
.git/hooks/pre-commit: 29: tools/pre-commit.sh: [[: not found
.git/hooks/pre-commit: 32: tools/pre-commit.sh: Syntax error: "(" unexpected
```

The shell appears to be using `/bin/bash`. @ppark-twosixtech what OS are you on?

**Comment by lcadalzo** [comment] 2022-11-09 17:34
> Paul was also running into this issue:
> 
> ```
> $ git commit
> .git/hooks/pre-commit: 29: tools/pre-commit.sh: [[: not found
> .git/hooks/pre-commit: 32: tools/pre-commit.sh: Syntax error: "(" unexpected
> ```
> 
> The shell appears to be using `/bin/bash`. @ppark-twosixtech what OS are you on?

this is the same error I hit after, per Paul's instructions if I interpreted them correctly, changing my `.git/hooks/pre-commit` to 
```
. tools/pre-commit.sh
```

**Comment by ppark-twosixtech** [comment] 2022-11-09 17:38
@lcadalzo running from `noether`

**Comment by ppark-twosixtech** [comment] 2022-11-09 17:39
@davidslater `bash tools/pre-commit.sh` ran without issues

**Comment by lcadalzo** [comment] 2022-11-09 17:39
> Can confirm on `noether`. Does this work? If you replace it with: `bash tools/pre-commit.sh`

this does indeed work. It also, as we would hope, doesn't flag the intentionally incorrectly formatted (but unstaged) Python file I added to test

**Comment by davidslater** [comment] 2022-11-09 17:41
This also works for me:
`./tools/pre-commit.sh`

I'm not sure if there's a big difference

**Comment by christopherwoodall** [comment] 2022-11-09 18:17
This will change depending on your shell. It sounds like `noether` defaults to a bourne shell(sh)? We could add a shebang to `pre-commit` but I think updating the docs- as seen in issue 1752- should be enough.

**Closed** 2022-11-09 21:15 UTC
Labels: bug
