### ISSUE TITLE
Editing files in Armory/JupyterLab instance saves them as root even when --root flag unused

### ISSUE THREAD

**Issue by AngusG** [twosixlabs/armory#933] opened 2020-11-16 17:42 UTC
When I create or modify files in a jupyterlab instance launched with `armory launch pytorch --jupyter` they are being saved with `root` permissions, but I don't have root permissions on my workstation (which causes problems when I need to subsequently manipulate the files outside of docker). 

Note that I am __not__ using the `--root` flag, so this seems to be a bug.

Armory version 0.12.1

**Comment by davidslater** [comment] 2020-11-18 03:30
I can confirm the bug - can replicate on linux, though not mac.

**Comment by davidslater** [comment] 2020-11-18 03:35
It looks like this was an earlier design decision - we are definitely running jupyter as root inside the container, which is why you are getting that issue:
```
(armory) √ david.slater@mac0831:~/armory% armory launch pytorch --jupyter      
2020-11-17 19:34:02 mac0831.local armory.docker.management[82925] INFO ARMORY Instance 589bdcee49 created.
2020-11-17 19:34:02 mac0831.local armory.eval.evaluator[82925] WARNING Running Jupyter Lab as root inside the container.
```

Digging into why we are doing this.

**Comment by davidslater** [comment] 2020-11-18 04:22
Ah, yes, I recall now. This is a deeper issue with how jupyter initializes itself. Due to docker, when it is run as a non-root user, it tries to write to `/.jupyter` and `/.local`, which it doesn't have write access to. I think I've found a way to get around this by modifying environment variables.

**Comment by davidslater** [comment] 2020-11-18 04:26
Once this gets merged in, you will need to make sure that `.ipynb_checkpoints/` is either deleted or chmod to not be root.

**Closed** 2020-11-18 16:42 UTC
Labels: bug
