### ISSUE TITLE
Problem running preprocessor defenses.

### ISSUE THREAD

**Issue by manishbcd** [twosixlabs/armory#1058] opened 2021-05-10 14:28 UTC
Hello,

I'm able to run the ucf101_baseline_pretrained.json scenario, but ucf101_defended_baseline_pretrained.json gives me an error (details below). It looks like ART calls preprocessor.forward although preprocessing defenses implement --call-- instead. 

2021-05-08 02:44:13 1c3ed53aa258 armory.scenarios.base[7] ERROR Encountered error during scenario evaluation.
Traceback (most recent call last):
File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/base.py", line 84, in evaluate
config, num_eval_batches, skip_benign, skip_attack, skip_misclassified
File "/opt/conda/lib/python3.7/site-packages/armory/scenarios/video_ucf101_scenario.py", line 127, in _evaluate
y_pred = classifier.predict(x)
File "/opt/conda/lib/python3.7/site-packages/art/estimators/classification/classifier.py", line 71, in replacement_function
return fdict[func_name](self, *args, **kwargs)
File "/opt/conda/lib/python3.7/site-packages/art/estimators/classification/pytorch.py", line 285, in predict
x_preprocessed, _ = self._apply_preprocessing(x, y=None, fit=False)
File "/opt/conda/lib/python3.7/site-packages/art/estimators/pytorch.py", line 182, in _apply_preprocessing
x, y = chain_processes(x, y)
File "/opt/conda/lib/python3.7/site-packages/art/estimators/pytorch.py", line 177, in chain_processes
x, y = preprocess.forward(x, y)
File "/opt/conda/lib/python3.7/site-packages/art/defences/preprocessor/preprocessor.py", line 135, in forward
raise NotImplementedError
NotImplementedError

**Comment by lcadalzo** [comment] 2021-05-10 23:44
Hi Manish, thanks for reporting this bug (which I was able to reproduce). I've included a [PR](https://github.com/twosixlabs/armory/pull/1060) which should address the issue and contains more information on the source of the error.

**Comment by lcadalzo** [comment] 2021-05-11 22:38
Closing due to #1060

**Closed by lcadalzo** 2021-05-11 22:38 UTC
